version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=posgres_database_708a_user
      - POSTGRES_PASSWORD=xgjpQtW5m5jbITR9NPDwFmqXQXgk7G7T
      - POSTGRES_DB=posgres_database_708a
    ports:
      - 5432:5433

    restart: always


  ecommerce_api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce_Api/Dockerfile
 
    depends_on:
        - "app_db"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-clksb9maov6s738n3g80-a;Database=applicationdb_0u5v;Username=jermaine;Password=b0OfJlHRIVX2ccznWC7C2jOwbR4sx8QL;Port=5432;"
         - ASPNETCORE_URLS=http://+80;




