version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_db:
    image: postgres:latest
    container_name: app_db
      - POSTGRES_USER=posgres_database_708a_user
      - POSTGRES_PASSWORD=xgjpQtW5m5jbITR9NPDwFmqXQXgk7G7T
      - POSTGRES_DB=EcommerceDb
    ports:
      - 5432:5433

    restart: always


  ecommerce_api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce_Api/Dockerfile
 
    depends_on:
        - "app_db"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-clga11njc5ks73edbiag-a.oregon-postgres.render.com;Database=EcommerceDb;Username=posgres_database_708a_user;Password=xgjpQtW5m5jbITR9NPDwFmqXQXgk7G7T;Port=5432;"
         - ASPNETCORE_URLS=http://+80;




