name: My Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, testbranch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-clghhref27hc739kkt70
          api-key: rnd_opHPVmdaY46FRfLnWlcghqzSpV8B
